GCC_MAKEFILE = gccMakefile

.PHONY: all clean run run-train run-inference

all:
	$(MAKE) -f $(GCC_MAKEFILE) all

clean:
	$(MAKE) -f $(GCC_MAKEFILE) clean

run:
	$(MAKE) -f $(GCC_MAKEFILE) run

run-train:
	$(MAKE) -f $(GCC_MAKEFILE) run-train

run-inference:
	$(MAKE) -f $(GCC_MAKEFILE) run-inference