#!/usr/bin/env python3
"""
binary2text_weights.py — Convert a MiniVGGNet binary checkpoint to kernel/weights.c

Rewritten for the CURRENT MiniVGGNet architecture (4 conv + fc1/fc2 + bn1-5),
matching kernel/weights.h. The previous version targeted an obsolete
5-conv / 3-FC network and produced the wrong array names and sizes.

The binary file must be the raw fp32 stream written by save_alexnet() in main.c,
in this EXACT order (no header):

    conv1_weights, conv1_bias, conv2_weights, conv2_bias,
    conv3_weights, conv3_bias, conv4_weights, conv4_bias,
    fc1_weights,   fc1_bias,   fc2_weights,   fc2_bias,
    bn1_gamma, bn1_beta, bn2_gamma, bn2_beta,
    bn3_gamma, bn3_beta, bn4_gamma, bn4_beta,
    bn5_gamma, bn5_beta
    [optional trailer: bn1..bn5 running mean/var  — ignored here]

Only the parameters above are emitted into weights.c. BN *running* mean/var are
NOT part of weights.c (they live in batchnorm_layer.c and only matter for
inference-mode BN; the Spike fine-tune runs in training mode with batch stats).

Usage:
    python3 scripts/binary2text_weights.py [weights_file] [variant] [out_layer]

    weights_file : path to binary        (default: minivgg.weights)
    variant      : alpha | full          (default: alpha)
    out_layer    : 10 | 100              (default: 100)

Examples:
    python3 scripts/binary2text_weights.py minivgg.weights alpha 100
    python3 scripts/binary2text_weights.py vggnet.weights  full  10
"""

import os
import sys
from array import array

# Width presets (must mirror the Makefile VARIANT defines and alexnet.h).
#   alpha : C1=12 C2=24 FC1=192   (~324,400 params, default Spike build)
#   full  : C1=32 C2=64 FC1=512
VARIANTS = {
    "alpha": dict(C1=12, C2=24, FC1=192),
    "full":  dict(C1=32, C2=64, FC1=512),
}

IN_CHANNELS = 3
K = 3
KK = K * K
POOL2 = 8  # spatial size feeding fc1 (C2 * 8 * 8)


def main():
    weights_file = sys.argv[1] if len(sys.argv) > 1 else "minivgg.weights"
    variant_name = sys.argv[2] if len(sys.argv) > 2 else "alpha"
    out_layer    = int(sys.argv[3]) if len(sys.argv) > 3 else 100

    if variant_name not in VARIANTS:
        sys.exit(f"Unknown variant '{variant_name}'. Choose: {list(VARIANTS)}")

    v = VARIANTS[variant_name]
    C1, C2, FC1 = v["C1"], v["C2"], v["FC1"]
    FC1_IN = C2 * POOL2 * POOL2

    # (C symbol, element count) in save_alexnet() order.
    layout = [
        ("conv1_weights", C1 * IN_CHANNELS * KK), ("conv1_bias", C1),
        ("conv2_weights", C1 * C1 * KK),          ("conv2_bias", C1),
        ("conv3_weights", C2 * C1 * KK),          ("conv3_bias", C2),
        ("conv4_weights", C2 * C2 * KK),          ("conv4_bias", C2),
        ("fc1_weights",   FC1_IN * FC1),          ("fc1_bias",   FC1),
        ("fc2_weights",   FC1 * out_layer),       ("fc2_bias",   out_layer),
        ("bn1_gamma", C1), ("bn1_beta", C1),
        ("bn2_gamma", C1), ("bn2_beta", C1),
        ("bn3_gamma", C2), ("bn3_beta", C2),
        ("bn4_gamma", C2), ("bn4_beta", C2),
        ("bn5_gamma", FC1), ("bn5_beta", FC1),
    ]
    expected = sum(n for _, n in layout)

    # Read the raw fp32 stream.
    data = array("f")
    with open(weights_file, "rb") as f:
        raw = f.read()
    data.frombytes(raw)
    if sys.byteorder != "little":
        data.byteswap()  # checkpoints are written little-endian

    n_have = len(data)
    running_stats = 2 * (C1 + C1 + C2 + C2 + FC1)  # optional trailer size
    if n_have == expected:
        print(f"{weights_file}: {n_have} floats (params only).")
    elif n_have == expected + running_stats:
        print(f"{weights_file}: {n_have} floats (params + BN running stats; "
              f"trailer ignored).")
    else:
        sys.exit(
            f"Size mismatch: {weights_file} has {n_have} floats, but the "
            f"'{variant_name}' / OUT_LAYER={out_layer} architecture expects "
            f"{expected} (or {expected + running_stats} with running stats). "
            f"Check the variant / out_layer arguments.")

    out_path = os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "kernel", "weights.c"))

    def fmt(vals):
        # %.9g round-trips fp32 exactly; append 'f' for float literals.
        return ", ".join(f"{x:.9g}f" for x in vals)

    pos = 0
    with open(out_path, "w") as f:
        f.write("//\n// File:        weights.c\n")
        f.write("// Description: MiniVGGNet parameters embedded from a trained checkpoint.\n")
        f.write(f"// Generated by scripts/binary2text_weights.py from "
                f"'{os.path.basename(weights_file)}'\n")
        f.write(f"// variant={variant_name}  (C1={C1} C2={C2} FC1={FC1})  "
                f"OUT_LAYER={out_layer}\n//\n")
        f.write('#include "alexnet.h"\n#include "weights.h"\n\n')
        for name, n in layout:
            seg = data[pos:pos + n]
            pos += n
            f.write(f"float {name}[{n}] = {{ {fmt(seg)} }};\n")

    print(f"Wrote {out_path}  ({expected} params, {expected * 4 / 1024:.1f} KB of .data).")
    print("NOTE: build vggnet with the SAME variant/OUT_LAYER "
          f"(-DC1_CHANNELS={C1} -DC2_CHANNELS={C2} -DFC1_LAYER={FC1} -DOUT_LAYER={out_layer}).")


if __name__ == "__main__":
    main()
