#!/usr/bin/env python3
"""
binary2text_weights_fp16.py — Cut an fp32 MiniVGGNet checkpoint down to FP16
and emit kernel/weights.c with _Float16 arrays (for vggnet16).

This is the FP16 twin of scripts/binary2text_weights.py. Same checkpoint
layout, same array names/sizes — the only differences are:

  * every value is rounded to IEEE-754 half (binary16) via struct 'e', so the
    emitted decimals ARE the exact fp16 values the C compiler will store; and
  * the C type is _Float16, not float (matches the fp16 net in alexnet.h /
    weights.h).

Values that overflow fp16's ~65504 range are clamped and reported (a real
checkpoint should never contain them, but a corrupt/rescaled one might).

Usage:
    python3 scripts/binary2text_weights_fp16.py [weights_file] [variant] [out_layer]

    weights_file : fp32 binary checkpoint  (default: minivgg.weights)
    variant      : alpha | full            (default: alpha)
    out_layer    : 10 | 100                (default: 100)

Example:
    python3 scripts/binary2text_weights_fp16.py minivgg.weights alpha 100
"""

import os
import sys
import struct
from array import array

# Must mirror the Makefile VARIANT defines and alexnet.h.
VARIANTS = {
    "alpha": dict(C1=12, C2=24, FC1=192),
    "full":  dict(C1=32, C2=64, FC1=512),
}

IN_CHANNELS = 3
K = 3
KK = K * K
POOL2 = 8  # spatial size feeding fc1 (C2 * 8 * 8)

FP16_MAX = 65504.0
_clamped = 0


def to_fp16(x):
    """Round a Python float to the nearest IEEE-754 half, returned as a float
    holding exactly that half value. Clamps out-of-range magnitudes."""
    global _clamped
    if x != x or x in (float("inf"), float("-inf")) or abs(x) > FP16_MAX:
        _clamped += 1
        x = FP16_MAX if x > 0 else -FP16_MAX
    # round-trip through the 16-bit 'e' format -> value is now an exact fp16
    return struct.unpack("<e", struct.pack("<e", x))[0]


def main():
    weights_file = sys.argv[1] if len(sys.argv) > 1 else "minivgg.weights"
    variant_name = sys.argv[2] if len(sys.argv) > 2 else "alpha"
    out_layer    = int(sys.argv[3]) if len(sys.argv) > 3 else 100

    if variant_name not in VARIANTS:
        sys.exit(f"Unknown variant '{variant_name}'. Choose: {list(VARIANTS)}")

    v = VARIANTS[variant_name]
    C1, C2, FC1 = v["C1"], v["C2"], v["FC1"]
    FC1_IN = C2 * POOL2 * POOL2

    # (C symbol, element count) in save_alexnet() order.
    layout = [
        ("conv1_weights", C1 * IN_CHANNELS * KK), ("conv1_bias", C1),
        ("conv2_weights", C1 * C1 * KK),          ("conv2_bias", C1),
        ("conv3_weights", C2 * C1 * KK),          ("conv3_bias", C2),
        ("conv4_weights", C2 * C2 * KK),          ("conv4_bias", C2),
        ("fc1_weights",   FC1_IN * FC1),          ("fc1_bias",   FC1),
        ("fc2_weights",   FC1 * out_layer),       ("fc2_bias",   out_layer),
        ("bn1_gamma", C1), ("bn1_beta", C1),
        ("bn2_gamma", C1), ("bn2_beta", C1),
        ("bn3_gamma", C2), ("bn3_beta", C2),
        ("bn4_gamma", C2), ("bn4_beta", C2),
        ("bn5_gamma", FC1), ("bn5_beta", FC1),
    ]
    expected = sum(n for _, n in layout)

    # Read the raw fp32 stream.
    data = array("f")
    with open(weights_file, "rb") as f:
        raw = f.read()
    data.frombytes(raw)
    if sys.byteorder != "little":
        data.byteswap()

    n_have = len(data)
    running_stats = 2 * (C1 + C1 + C2 + C2 + FC1)
    if n_have == expected:
        print(f"{weights_file}: {n_have} floats (params only).")
    elif n_have == expected + running_stats:
        print(f"{weights_file}: {n_have} floats (params + BN running stats; "
              f"trailer ignored).")
    else:
        sys.exit(
            f"Size mismatch: {weights_file} has {n_have} floats, but the "
            f"'{variant_name}' / OUT_LAYER={out_layer} architecture expects "
            f"{expected} (or {expected + running_stats} with running stats).")

    out_path = os.path.normpath(
        os.path.join(os.path.dirname(__file__), "..", "kernel", "weights.c"))

    def fmt(vals):
        # Plain decimal, NO 'f16' suffix: %.6g of an already-fp16-rounded value
        # round-trips exactly, and a suffix-less literal (int- or double-typed)
        # converts to _Float16 on array init without double-rounding error --
        # while avoiding invalid literals like `0f16`/`1f16` for whole values.
        return ", ".join(f"{to_fp16(x):.6g}" for x in vals)

    pos = 0
    with open(out_path, "w") as f:
        f.write("//\n// File:        weights.c\n")
        f.write("// Description: MiniVGGNet parameters (FP16) embedded from a trained checkpoint.\n")
        f.write(f"// Generated by scripts/binary2text_weights_fp16.py from "
                f"'{os.path.basename(weights_file)}'\n")
        f.write(f"// variant={variant_name}  (C1={C1} C2={C2} FC1={FC1})  "
                f"OUT_LAYER={out_layer}\n//\n")
        f.write('#include "alexnet.h"\n#include "weights.h"\n\n')
        for name, n in layout:
            seg = data[pos:pos + n]
            pos += n
            f.write(f"_Float16 {name}[{n}] = {{ {fmt(seg)} }};\n")

    print(f"Wrote {out_path}  ({expected} params, {expected * 2 / 1024:.1f} KB of .data).")
    if _clamped:
        print(f"WARNING: {_clamped} value(s) exceeded fp16 range and were clamped to +/-65504.")
    print("NOTE: build vggnet16 with the SAME variant/OUT_LAYER "
          f"(-DC1_CHANNELS={C1} -DC2_CHANNELS={C2} -DFC1_LAYER={FC1} -DOUT_LAYER={out_layer}).")


if __name__ == "__main__":
    main()
