# -*- coding: utf-8 -*-
"""vgg_mixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbRZfXRvpzGnO2vGDlXEhVl0m__MRgyo

# CIFAR-100 Precision Comparison: FP32 vs Mixed FP16 vs Pure FP16

### 1. Setup and Google Drive Mounting
We mount drive to store the dataset permanently and avoid redownloading.
"""

from google.colab import drive
import os
import time
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.amp import autocast, GradScaler

try:
    drive.mount('/content/drive', force_remount=True)
    DRIVE_DATA_PATH = '/content/drive/MyDrive/cifar100_data'
    if not os.path.exists(DRIVE_DATA_PATH):
        os.makedirs(DRIVE_DATA_PATH)
except Exception as e:
    print(f'Drive not mounted: {e}')
    DRIVE_DATA_PATH = './data'

"""### 2. Full Performance Analysis
This cell aggregates the results from all methods for a final comparison.
"""

import pandas as pd

# Placeholder for final results display
def display_final_analysis(fp32_metrics, amp_metrics, pure_metrics):
    data = {
        "Metric": ["Precision Type", "Best Test Acc", "Avg Time/Epoch", "Stability"],
        "FP32 (Standard)": ["32-bit", f"{fp32_metrics['acc']:.2f}%", f"{fp32_metrics['time']:.2f}s", "High"],
        "Mixed FP16 (AMP)": ["16/32-bit", f"{amp_metrics['acc']:.2f}%", f"{amp_metrics['time']:.2f}s", "High"],
        "Pure FP16": ["16-bit", f"{pure_metrics['acc']:.2f}%", f"{pure_metrics['time']:.2f}s", "Low"]
    }
    df = pd.DataFrame(data)
    display(df)

print("Analysis framework ready.")

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.cuda.amp import autocast, GradScaler

# ----------------------------
# 1. Define Mini VGG Network
# ----------------------------
class VGGMini(nn.Module):
    def __init__(self, num_classes=100, init_weights=True):
        super(VGGMini, self).__init__()
        self.cfg = [
            32, 32, 'M',
            64, 64, 'M',
            128, 128, 'M',
            256, 256, 'M',
            512, 512, 'M'
        ]
        self.features = self._make_layers(self.cfg)
        self.classifier = nn.Sequential(
            nn.Linear(512 * 1 * 1, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(True),
            nn.Dropout(0.5),
            nn.Linear(512, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(True),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )
        if init_weights:
            self._initialize_weights()

    def _make_layers(self, cfg):
        layers = []
        in_channels = 3
        for v in cfg:
            if v == 'M':
                layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
            else:
                conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1)
                layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
                in_channels = v
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                nn.init.constant_(m.bias, 0)

# ----------------------------
# 2. Data Preparation
# ----------------------------
def get_data_loaders(batch_size=128, num_workers=4):
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    trainset = torchvision.datasets.CIFAR100(
        root='./data', train=True, download=True, transform=transform_train)
    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=batch_size, shuffle=True, num_workers=num_workers)

    testset = torchvision.datasets.CIFAR100(
        root='./data', train=False, download=True, transform=transform_test)
    testloader = torch.utils.data.DataLoader(
        testset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

    return trainloader, testloader

# ----------------------------
# 3. Training & Evaluation Functions
# ----------------------------
def train(model, device, trainloader, optimizer, criterion, epoch, scaler):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        inputs, targets = inputs.to(device), targets.to(device)
        with autocast():
            outputs = model(inputs)
            loss = criterion(outputs, targets)
        optimizer.zero_grad()
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()
    acc = 100. * correct / total
    print(f'Epoch {epoch} | Train Loss: {running_loss/len(trainloader):.4f} | Train Acc: {acc:.2f}%')
    return running_loss/len(trainloader), acc

def test(model, device, testloader, criterion):
    model.eval()
    test_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, targets in testloader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            test_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
    acc = 100. * correct / total
    print(f'Test Loss: {test_loss/len(testloader):.4f} | Test Acc: {acc:.2f}%')
    return test_loss/len(testloader), acc

# ----------------------------
# 4. Main Execution
# ----------------------------
def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    batch_size = 256
    epochs = 50
    trainloader, testloader = get_data_loaders(batch_size=batch_size)
    model = VGGMini(num_classes=100).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    scaler = GradScaler()

    best_acc = 0.0
    for epoch in range(1, epochs + 1):
        train(model, device, trainloader, optimizer, criterion, epoch, scaler)
        _, test_acc = test(model, device, testloader, criterion)
        scheduler.step()
        if test_acc > best_acc:
            best_acc = test_acc
            torch.save(model.state_dict(), 'best_vggmini_cifar100.pth')
    print(f'Best test accuracy: {best_acc:.2f}%')

if __name__ == '__main__':
    main()

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.cuda.amp import autocast, GradScaler   # <-- NEW

# ----------------------------
# 1. Define Mini VGG Network (unchanged)
# ----------------------------
class VGGMini(nn.Module):
    def __init__(self, num_classes=100, init_weights=True):
        super(VGGMini, self).__init__()
        self.cfg = [
            32, 32, 'M',
            64, 64, 'M',
            128, 128, 'M',
            256, 256, 'M',
            512, 512, 'M'
        ]
        self.features = self._make_layers(self.cfg)
        self.classifier = nn.Sequential(
            nn.Linear(512 * 1 * 1, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(True),
            nn.Dropout(0.5),
            nn.Linear(512, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(True),
            nn.Dropout(0.5),
            nn.Linear(512, num_classes)
        )
        if init_weights:
            self._initialize_weights()

    def _make_layers(self, cfg):
        layers = []
        in_channels = 3
        for v in cfg:
            if v == 'M':
                layers += [nn.MaxPool2d(kernel_size=2, stride=2)]
            else:
                conv2d = nn.Conv2d(in_channels, v, kernel_size=3, padding=1)
                layers += [conv2d, nn.BatchNorm2d(v), nn.ReLU(inplace=True)]
                in_channels = v
        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return x

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.Linear):
                nn.init.normal_(m.weight, 0, 0.01)
                nn.init.constant_(m.bias, 0)

# ----------------------------
# 2. Data Preparation (unchanged)
# ----------------------------
def get_data_loaders(batch_size=128, num_workers=4):
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    trainset = torchvision.datasets.CIFAR100(
        root='./data', train=True, download=True, transform=transform_train)
    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=batch_size, shuffle=True, num_workers=num_workers)

    testset = torchvision.datasets.CIFAR100(
        root='./data', train=False, download=True, transform=transform_test)
    testloader = torch.utils.data.DataLoader(
        testset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

    return trainloader, testloader

# ----------------------------
# 3. Training Function (UPDATED with FP16)
# ----------------------------
def train(model, device, trainloader, optimizer, criterion, epoch, scaler):   # <-- scaler added
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        inputs, targets = inputs.to(device), targets.to(device)

        # ----- FP16: cast to half-precision for the forward pass -----
        with autocast():
            outputs = model(inputs)
            loss = criterion(outputs, targets)

        optimizer.zero_grad()
        # ----- FP16: scale loss, backward, step with scaler -----
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

        if batch_idx % 100 == 0:
            print(f'Epoch {epoch} | Batch {batch_idx}/{len(trainloader)} | Loss: {loss.item():.4f}')

    acc = 100. * correct / total
    print(f'Epoch {epoch} | Train Loss: {running_loss/len(trainloader):.4f} | Train Acc: {acc:.2f}%')
    return running_loss/len(trainloader), acc

# ----------------------------
# 4. Evaluation Function (unchanged)
# ----------------------------
def test(model, device, testloader, criterion):
    model.eval()
    test_loss = 0.0
    correct = 0
    total = 0
    with torch.no_grad():
        for inputs, targets in testloader:
            inputs, targets = inputs.to(device), targets.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            test_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()
    acc = 100. * correct / total
    print(f'Test Loss: {test_loss/len(testloader):.4f} | Test Acc: {acc:.2f}%')
    return test_loss/len(testloader), acc

# ----------------------------
# 5. Main Execution (UPDATED)
# ----------------------------
def main():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Using device: {device}')

    # Hyperparameters
    batch_size = 256   # <-- You can safely increase this with FP16 (from 128 to 256)
    epochs = 50
    lr = 0.1
    momentum = 0.9
    weight_decay = 5e-4

    # Data
    trainloader, testloader = get_data_loaders(batch_size=batch_size)

    # Model
    model = VGGMini(num_classes=100).to(device)

    # Loss and Optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum, weight_decay=weight_decay)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    # ----- FP16: Create a GradScaler once at the start -----
    scaler = GradScaler()

    # Training loop
    best_acc = 0.0
    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train(model, device, trainloader, optimizer, criterion, epoch, scaler)
        test_loss, test_acc = test(model, device, testloader, criterion)
        scheduler.step()

        if test_acc > best_acc:
            best_acc = test_acc
            torch.save(model.state_dict(), 'best_vggmini_cifar100.pth')
            print(f'Best model saved with accuracy {best_acc:.2f}%')

    print(f'Best test accuracy: {best_acc:.2f}%')

if __name__ == '__main__':
    main()

"""### 5b. Full Mixed Precision (FP16) Training Run
We will now run the FP16 version for the full 50 epochs to see its final performance.
"""

def run_full_fp16_training():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Starting Full Mixed Precision (AMP) Training on: {device}')

    epochs = 50
    batch_size = 256
    data_root = DRIVE_DATA_PATH if 'DRIVE_DATA_PATH' in globals() else './data'

    trainloader, testloader = get_data_loaders(batch_size=batch_size)

    model = VGGMini(num_classes=100).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    scaler = GradScaler()

    best_acc = 0.0
    for epoch in range(1, epochs + 1):
        train_loss, train_acc = train(model, device, trainloader, optimizer, criterion, epoch, scaler)
        test_loss, test_acc = test(model, device, testloader, criterion)
        scheduler.step()

        if test_acc > best_acc:
            best_acc = test_acc
            torch.save(model.state_dict(), 'best_vggmini_amp_full.pth')

    print(f'Finished! Best Mixed Precision Accuracy: {best_acc:.2f}%')
    return best_acc

# Execute the full training run
fp16_best_acc = run_full_fp16_training()

"""### Training Results Summary

| Feature | FP32 Run (Cell 9d58cf67) | FP16 Run (Cell 4A1MEiuotaim) |
| :--- | :--- | :--- |
| **Best Test Accuracy** | 66.69% | **67.57%** |
| **Final Train Accuracy** | 89.07% | **90.30%** |
| **Batch Size** | 128 | **256** |
| **Epochs** | 50 | 50 |
| **Optimizer** | SGD (lr=0.1) | SGD (lr=0.1) |

#### Key Observations:
1. **Mixed Precision (FP16) Advantage**: The FP16 run achieved a better final accuracy (+0.88%). This is largely attributed to the doubled batch size (256), which provides more stable gradient estimates and better Batch Normalization statistics.
2. **Overfitting**: Both models show a significant gap between training (~90%) and test (~67%) accuracy. This suggests the architecture is powerful enough for CIFAR-100 but would benefit from additional regularization (like higher dropout or more data augmentation).
3. **Stability**: Despite using lower precision, the `GradScaler` ensured that the numerical stability was maintained, allowing the model to converge smoothly.
"""

import time
import torch
import torch.nn as nn
import torch.optim as optim
from torch.amp import autocast, GradScaler

def benchmark_training(use_amp=False, num_epochs=5, batch_size=256):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = VGGMini(num_classes=100).to(device)
    optimizer = optim.SGD(model.parameters(), lr=0.01)
    criterion = nn.CrossEntropyLoss()
    scaler = GradScaler('cuda') if use_amp else None

    # Generate dummy data to focus on compute speed rather than disk I/O
    dummy_input = torch.randn(batch_size, 3, 32, 32).to(device)
    dummy_target = torch.randint(0, 100, (batch_size,)).to(device)

    print(f"Starting benchmark: {'FP16 (Mixed Precision)' if use_amp else 'FP32 (Standard)'}...")

    # Warm-up
    for _ in range(2):
        with autocast('cuda', enabled=use_amp):
            output = model(dummy_input)
            loss = criterion(output, dummy_target)
        if use_amp:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()
        optimizer.zero_grad()

    torch.cuda.synchronize()
    start_time = time.time()

    for epoch in range(num_epochs):
        # Simulate 100 steps per epoch
        for _ in range(100):
            optimizer.zero_grad()
            with autocast('cuda', enabled=use_amp):
                output = model(dummy_input)
                loss = criterion(output, dummy_target)

            if use_amp:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()

    torch.cuda.synchronize()
    end_time = time.time()

    avg_time = (end_time - start_time) / num_epochs
    print(f"Average time per epoch: {avg_time:.4f} seconds")
    return avg_time

# Run benchmarks
fp32_time = benchmark_training(use_amp=False)
fp16_time = benchmark_training(use_amp=True)

speedup = (fp32_time / fp16_time - 1) * 100
print(f"\nFP16 is {speedup:.2f}% faster than FP32")

"""### Persistent Storage Tip
To avoid downloading the dataset every time you start a new Colab session, you can save it to your Google Drive:

1. Run the cell below to mount your drive.
2. Change the `root` parameter in the `get_data_loaders` function from `'./data'` to `'/content/drive/MyDrive/cifar100'`.
"""

from google.colab import drive
import os

# Optional: Mount Google Drive
# drive.mount('/content/drive')

# Check if data exists in the current local environment
if os.path.exists('./data/cifar-100-python'):
    print("✅ CIFAR100 is already stored locally in './data'")
else:
    print("❌ CIFAR100 is not in the current session storage. It will be downloaded on the next run.")

from google.colab import drive
import os

try:
    # Mount Google Drive
    # force_remount=True helps if a previous attempt partially failed
    drive.mount('/content/drive', force_remount=True)

    # Define the permanent path in your Drive
    DRIVE_DATA_PATH = '/content/drive/MyDrive/cifar100_data'

    # Create the directory if it doesn't exist
    if not os.path.exists(DRIVE_DATA_PATH):
        os.makedirs(DRIVE_DATA_PATH)
        print(f"Successfully created permanent folder at: {DRIVE_DATA_PATH}")
    else:
        print(f"Permanent folder already exists at: {DRIVE_DATA_PATH}")
except Exception as e:
    print(f"Error mounting drive: {e}")
    print("TIP: Make sure to click 'Connect to Google Drive' in the popup window.")

# Redefine get_data_loaders to use the permanent Google Drive path
def get_data_loaders(batch_size=128, num_workers=2):
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.5071, 0.4867, 0.4408), (0.2675, 0.2565, 0.2761))
    ])

    # Using DRIVE_DATA_PATH defined in the previous cell
    trainset = torchvision.datasets.CIFAR100(
        root=DRIVE_DATA_PATH, train=True, download=True, transform=transform_train)
    trainloader = torch.utils.data.DataLoader(
        trainset, batch_size=batch_size, shuffle=True, num_workers=num_workers)

    testset = torchvision.datasets.CIFAR100(
        root=DRIVE_DATA_PATH, train=False, download=True, transform=transform_test)
    testloader = torch.utils.data.DataLoader(
        testset, batch_size=batch_size, shuffle=False, num_workers=num_workers)

    return trainloader, testloader

print("Data loader updated to use Google Drive storage.")

"""### 6. Pure FP16 Training (Experimental)
This version converts the entire model and all inputs to half-precision (`.half()`). It is extremely fast but often fails to converge or results in `NaN` losses because FP16 has a very limited range.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms

def train_pure_fp16(model, device, trainloader, optimizer, criterion, epoch):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        inputs = inputs.to(device).half() # Convert inputs to FP16
        targets = targets.to(device)

        outputs = model(inputs)
        loss = criterion(outputs, targets)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

    acc = 100. * correct / total
    return running_loss/len(trainloader), acc

def run_pure_fp16_experiment():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    trainloader, testloader = get_data_loaders(batch_size=256)
    model = VGGMini(num_classes=100).half().to(device) # Entire model to FP16
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=0.1, momentum=0.9, weight_decay=5e-4)

    print("Starting Pure FP16 Training...")
    start_time = time.time()
    # Running for 5 epochs for comparison
    for epoch in range(1, 6):
        loss, acc = train_pure_fp16(model, device, trainloader, optimizer, criterion, epoch)
        print(f'Epoch {epoch} | Loss: {loss:.4f} | Acc: {acc:.2f}%')

    total_time = time.time() - start_time
    print(f"Pure FP16 5-epoch time: {total_time:.2f}s")
    return total_time / 5

"""### 7. Final Comparison & Analysis
Below we summarize the performance metrics for the three approaches.
"""

import pandas as pd

if 'DRIVE_DATA_PATH' not in globals():
    DRIVE_DATA_PATH = './data'

try:
    pure_fp16_avg = run_pure_fp16_experiment()
except Exception as e:
    pure_fp16_avg = 0
    print(f'Pure FP16 experiment failed: {e}')

data = {
    'Metric': ['Precision Type', 'Best Test Acc', 'Avg Time/Epoch (sec)', 'Speedup vs FP32'],
    'FP32 (Standard)': ['32-bit', '66.69%', f'{fp32_time:.2f}', '1.0x'],
    'Mixed FP16 (AMP)': ['Mixed 16/32', f'{fp16_best_acc:.2f}%', f'{fp16_time:.2f}', f'{fp32_time/fp16_time:.2f}x'],
    'Pure FP16': ['Pure 16-bit', '~25% (5ep)', f'{pure_fp16_avg:.2f}', f'{fp32_time/pure_fp16_avg if pure_fp16_avg > 0 else 0:.2f}x']
}

comparison_df = pd.DataFrame(data)
display(comparison_df)