#!/usr/bin/env python3
import argparse
from pathlib import Path

import numpy as np

INPUTS = 2048
OUTPUTS = 512
SAMPLES = 4


def write_c_array_f32(f, name: str, arr: np.ndarray, per_line: int = 8) -> None:
    flat = arr.astype(np.float32).reshape(-1)
    f.write(f"float {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        vals = ", ".join(f"{x:.8f}f" for x in chunk)
        if i + per_line >= flat.size:
            f.write(f"    {vals}\n")
        else:
            f.write(f"    {vals},\n")
    f.write("};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate FC(2048->512) synthetic vectors for bare-metal tests")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--out-dir", default="generated_data", help="Output directory for binary files")
    parser.add_argument("--weights-c", default="kernel/weights.c", help="Path to generated weights.c")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    # X: [4, 2048], float32 in [-1.0, 1.0]
    x = rng.uniform(-1.0, 1.0, size=(SAMPLES, INPUTS)).astype(np.float32)

    # W: [2048*512], float32 in [-0.1, 0.1]
    w = rng.uniform(-0.1, 0.1, size=(INPUTS * OUTPUTS,)).astype(np.float32)

    # B: [512], float32 all ones
    b = np.ones((OUTPUTS,), dtype=np.float32)

    # Labels: [4], int32 in [0, 511]
    labels = rng.integers(0, OUTPUTS, size=(SAMPLES,), dtype=np.int32)

    # Extra helper for MSE mode: one-hot targets [4, 512]
    targets = np.zeros((SAMPLES, OUTPUTS), dtype=np.float32)
    targets[np.arange(SAMPLES), labels] = 1.0

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # CRITICAL exports requested by user
    x.tofile(out_dir / "inputs.bin")
    labels.tofile(out_dir / "labels.bin")

    # Additional export used when compiling with SET_MSE
    targets.tofile(out_dir / "targets.bin")

    weights_path = Path(args.weights_c)
    weights_path.parent.mkdir(parents=True, exist_ok=True)

    with weights_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by scripts/generate_fc_test_vectors.py\n\n")
        write_c_array_f32(f, "fc1_weights", w)
        write_c_array_f32(f, "fc1_bias", b)

    print(f"Generated: {out_dir / 'inputs.bin'}")
    print(f"Generated: {out_dir / 'labels.bin'}")
    print(f"Generated: {out_dir / 'targets.bin'}")
    print(f"Generated: {weights_path}")


if __name__ == "__main__":
    main()
