#!/usr/bin/env python3
import argparse
from pathlib import Path

import numpy as np

BATCH = 4
C_IN = 43
C_OUT = 43
KERNEL = 3
H_IN = 8
W_IN = 8
PADDING = 1
STRIDE = 1
H_OUT = 8
W_OUT = 8

INPUT_ELEMS = C_IN * H_IN * W_IN
OUTPUT_ELEMS = C_OUT * H_OUT * W_OUT
WEIGHT_ELEMS = C_OUT * C_IN * KERNEL * KERNEL


def write_c_array_f32(f, name: str, arr: np.ndarray, per_line: int = 8) -> None:
    flat = arr.astype(np.float32).reshape(-1)
    f.write(f"float {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        vals = ", ".join(f"{x:.8f}f" for x in chunk)
        if i + per_line >= flat.size:
            f.write(f"    {vals}\n")
        else:
            f.write(f"    {vals},\n")
    f.write("};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CONV(43->43, 3x3, 8x8) synthetic vectors")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--out-dir", default="generated_data", help="Output directory for binary files")
    parser.add_argument("--weights-c", default="kernel/weights.c", help="Path to generated weights.c")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    inputs = rng.uniform(-1.0, 1.0, size=(BATCH, INPUT_ELEMS)).astype(np.float32)
    targets = rng.uniform(-1.0, 1.0, size=(BATCH, OUTPUT_ELEMS)).astype(np.float32)
    labels = rng.integers(0, C_OUT, size=(BATCH,), dtype=np.int32)

    weights = rng.uniform(-0.1, 0.1, size=(WEIGHT_ELEMS,)).astype(np.float32)
    bias = np.ones((C_OUT,), dtype=np.float32)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    inputs.tofile(out_dir / "inputs.bin")
    targets.tofile(out_dir / "targets.bin")
    labels.tofile(out_dir / "labels.bin")

    weights_path = Path(args.weights_c)
    weights_path.parent.mkdir(parents=True, exist_ok=True)

    with weights_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by scripts/generate_conv_test_vectors.py\n\n")
        write_c_array_f32(f, "conv1_weights", weights)
        write_c_array_f32(f, "conv1_bias", bias)

    print(f"Generated: {out_dir / 'inputs.bin'}")
    print(f"Generated: {out_dir / 'targets.bin'}")
    print(f"Generated: {out_dir / 'labels.bin'}")
    print(f"Generated: {weights_path}")


if __name__ == "__main__":
    main()
