"""
gen_zero_weights.py — Generate kernel/weights.c with trivial initial values.

Values:  conv/fc weights=0, biases=0, BN gamma=1, BN beta/mean=0, BN var=1
These are overwritten at runtime by gauss_initialization() in TRAIN mode.
The file just needs to have the correct array sizes so the linker is happy.

Usage:
    python3 scripts/gen_zero_weights.py [variant] [out_layer]

    variant   : full | small | tiny  (default: full)
    out_layer : 10   | 100           (default: 10)

Examples:
    python3 scripts/gen_zero_weights.py tiny 10    # Tiny + CIFAR-10
    python3 scripts/gen_zero_weights.py tiny 100   # Tiny + CIFAR-100
    python3 scripts/gen_zero_weights.py full 10    # Full + CIFAR-10
"""

import os, sys

VARIANTS = {
    "full":  dict(C1=32,  C2=64,  C3=128, C4=256, C5=512, FC6=512, FC7=512),
    "small": dict(C1=16,  C2=32,  C3=64,  C4=128, C5=256, FC6=256, FC7=256),
    "tiny":  dict(C1=8,   C2=16,  C3=32,  C4=64,  C5=128, FC6=128, FC7=128),
}

variant_name = sys.argv[1] if len(sys.argv) > 1 else "full"
out_layer    = int(sys.argv[2]) if len(sys.argv) > 2 else 10

if variant_name not in VARIANTS:
    print(f"Unknown variant '{variant_name}'. Choose: {list(VARIANTS)}")
    sys.exit(1)

v = VARIANTS[variant_name]
C1, C2, C3, C4, C5 = v["C1"], v["C2"], v["C3"], v["C4"], v["C5"]
FC6, FC7 = v["FC6"], v["FC7"]
IN, K, P5 = 3, 3, 1   # input channels, kernel size, pooling5 spatial

layers = [
    {"name": "conv1",  "type": "conv", "in": IN,  "out": C1,  "k": K},
    {"name": "conv1b", "type": "conv", "in": C1,  "out": C1,  "k": K},
    {"name": "conv2",  "type": "conv", "in": C1,  "out": C2,  "k": K},
    {"name": "conv2b", "type": "conv", "in": C2,  "out": C2,  "k": K},
    {"name": "conv3",  "type": "conv", "in": C2,  "out": C3,  "k": K},
    {"name": "conv3b", "type": "conv", "in": C3,  "out": C3,  "k": K},
    {"name": "conv4",  "type": "conv", "in": C3,  "out": C4,  "k": K},
    {"name": "conv4b", "type": "conv", "in": C4,  "out": C4,  "k": K},
    {"name": "conv5",  "type": "conv", "in": C4,  "out": C5,  "k": K},
    {"name": "conv5b", "type": "conv", "in": C5,  "out": C5,  "k": K},
    {"name": "fc1",    "type": "fc",   "in": C5 * P5 * P5, "out": FC6},
    {"name": "fc2",    "type": "fc",   "in": FC6, "out": FC7},
    {"name": "fc3",    "type": "fc",   "in": FC7, "out": out_layer},
    {"name": "bn1",    "type": "bn",   "units": C1},
    {"name": "bn1b",   "type": "bn",   "units": C1},
    {"name": "bn2",    "type": "bn",   "units": C2},
    {"name": "bn2b",   "type": "bn",   "units": C2},
    {"name": "bn3",    "type": "bn",   "units": C3},
    {"name": "bn3b",   "type": "bn",   "units": C3},
    {"name": "bn4",    "type": "bn",   "units": C4},
    {"name": "bn4b",   "type": "bn",   "units": C4},
    {"name": "bn5",    "type": "bn",   "units": C5},
    {"name": "bn5b",   "type": "bn",   "units": C5},
    {"name": "bn6",    "type": "bn",   "units": FC6},
    {"name": "bn7",    "type": "bn",   "units": FC7},
]

def zeros(n): return ", ".join(["0.0f"] * n)
def ones(n):  return ", ".join(["1.0f"] * n)

out_path = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "kernel", "weights.c"))
print(f"Generating {out_path}  [variant={variant_name}, OUT_LAYER={out_layer}] ...")

with open(out_path, "w") as f:
    f.write(f"// Auto-generated by scripts/gen_zero_weights.py\n")
    f.write(f"// variant={variant_name}  OUT_LAYER={out_layer}\n\n")

    for layer in layers:
        name = layer["name"]
        f.write(f"// --- {name.upper()} ---\n")
        if layer["type"] == "conv":
            nw = layer["out"] * layer["in"] * layer["k"] * layer["k"]
            nb = layer["out"]
            f.write(f"float {name}_weights[{nw}] = {{ {zeros(nw)} }};\n")
            f.write(f"float {name}_bias[{nb}] = {{ {zeros(nb)} }};\n\n")
        elif layer["type"] == "fc":
            nw = layer["out"] * layer["in"]
            nb = layer["out"]
            f.write(f"float {name}_weights[{nw}] = {{ {zeros(nw)} }};\n")
            f.write(f"float {name}_bias[{nb}] = {{ {zeros(nb)} }};\n\n")
        elif layer["type"] == "bn":
            u = layer["units"]
            f.write(f"float {name}_gamma[{u}] = {{ {ones(u)} }};\n")
            f.write(f"float {name}_beta[{u}]  = {{ {zeros(u)} }};\n")
            f.write(f"float {name}_mean[{u}]  = {{ {zeros(u)} }};\n")
            f.write(f"float {name}_var[{u}]   = {{ {ones(u)} }};\n\n")

total = sum(
    layer["out"] * layer["in"] * layer["k"]**2 + layer["out"] if layer["type"] == "conv"
    else layer["out"] * layer["in"] + layer["out"]             if layer["type"] == "fc"
    else layer["units"] * 4
    for layer in layers
)
print(f"Done. Total floats: {total:,}  ({total*4/1024/1024:.1f} MB)")
