#!/usr/bin/env python3
"""Convert an image list file into traversable C dataset arrays.

Input list format (one sample per line):
    <label> <image_path>

Example:
    4 /home/user/cifar10_images/deer/train_0001.jpg
"""

import argparse
import os
import re
import sys
from typing import List, Optional, Tuple

from PIL import Image


def parse_list_file(list_path: str) -> List[Tuple[int, str]]:
    """Parse '<label> <path>' lines; skip blanks/comments/malformed lines."""
    samples: List[Tuple[int, str]] = []

    with open(list_path, "r", encoding="utf-8") as f:
        for line_no, raw_line in enumerate(f, start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split(maxsplit=1)
            if len(parts) != 2:
                print(
                    f"[warn] Skipping malformed line {line_no}: {raw_line.rstrip()}",
                    file=sys.stderr,
                )
                continue

            label_str, img_path = parts
            try:
                label = int(label_str)
            except ValueError:
                print(
                    f"[warn] Skipping line {line_no}: label is not integer ({label_str!r})",
                    file=sys.stderr,
                )
                continue

            samples.append((label, img_path))

    return samples


def resolve_img_path(raw_path: str, list_dir: str) -> str:
    expanded = os.path.expanduser(raw_path)
    if os.path.isabs(expanded):
        return expanded
    return os.path.normpath(os.path.join(list_dir, expanded))


def make_identifier(text: str) -> str:
    identifier = re.sub(r"[^0-9a-zA-Z_]", "_", text)
    if not identifier:
        return "dataset"
    if identifier[0].isdigit():
        return "_" + identifier
    return identifier


def write_unsigned_char_array(f, array_name: str, raw_bytes: bytes) -> None:
    f.write(f"const unsigned char {array_name}[] = {{\n")
    ints_per_line = 15

    for i in range(0, len(raw_bytes), ints_per_line):
        chunk = raw_bytes[i : i + ints_per_line]
        line = ", ".join(str(b) for b in chunk)
        trailing = "," if i + ints_per_line < len(raw_bytes) else ""
        f.write(f"    {line}{trailing}\n")

    f.write("};\n\n")


def write_unsigned_int_array(f, array_name: str, values: List[int]) -> None:
    f.write(f"const unsigned int {array_name}[] = {{\n")
    ints_per_line = 12

    for i in range(0, len(values), ints_per_line):
        chunk = values[i : i + ints_per_line]
        line = ", ".join(str(v) for v in chunk)
        trailing = "," if i + ints_per_line < len(values) else ""
        f.write(f"    {line}{trailing}\n")

    f.write("};\n\n")


def write_int_array(f, array_name: str, values: List[int]) -> None:
    f.write(f"const int {array_name}[] = {{\n")
    ints_per_line = 12

    for i in range(0, len(values), ints_per_line):
        chunk = values[i : i + ints_per_line]
        line = ", ".join(str(v) for v in chunk)
        trailing = "," if i + ints_per_line < len(values) else ""
        f.write(f"    {line}{trailing}\n")

    f.write("};\n\n")


def infer_header_path(output_path: str, header_path: Optional[str]) -> str:
    if header_path:
        return header_path

    root, _ = os.path.splitext(output_path)
    return root + ".h"


def make_header_guard(header_path: str, prefix_id: str) -> str:
    base = os.path.basename(header_path)
    guard = f"{prefix_id}_{base}"
    guard = re.sub(r"[^0-9a-zA-Z_]", "_", guard)
    guard = guard.upper()
    if guard and guard[0].isdigit():
        guard = "_" + guard
    return guard


def write_header_file(
    header_path: str,
    prefix_id: str,
    image_count: int,
    width: int,
    height: int,
    channels: int,
) -> None:
    guard = make_header_guard(header_path, prefix_id)

    with open(header_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/list_to_c_arrays.py\n")
        f.write("// Dataset arrays for in-memory image traversal.\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write("#include <stddef.h>\n\n")

        f.write(f"extern const int {prefix_id}_count;\n")
        f.write(f"extern const int {prefix_id}_w;\n")
        f.write(f"extern const int {prefix_id}_h;\n")
        f.write(f"extern const int {prefix_id}_c;\n")
        f.write(f"extern const int {prefix_id}_image_bytes;\n")
        f.write(f"extern const unsigned int {prefix_id}_total_bytes;\n\n")

        f.write(f"extern const unsigned char {prefix_id}_data[];\n")
        f.write(f"extern const unsigned int {prefix_id}_offsets[{image_count + 1}];\n")
        f.write(f"extern const int {prefix_id}_labels[{image_count}];\n\n")

        f.write("// Access pattern:\n")
        f.write(
            f"//   img_ptr = {prefix_id}_data + {prefix_id}_offsets[i];\n"
        )
        f.write(
            f"//   img_len = {prefix_id}_offsets[i+1] - {prefix_id}_offsets[i];\n"
        )
        f.write(f"//   label   = {prefix_id}_labels[i];\n\n")

        f.write(f"#endif  // {guard}\n")


def convert_list_to_c(
    list_path: str,
    output_path: str,
    header_path: Optional[str],
    prefix: str,
    max_images: int,
) -> int:
    list_path = os.path.abspath(os.path.expanduser(list_path))
    list_dir = os.path.dirname(list_path)
    samples = parse_list_file(list_path)

    if max_images > 0:
        samples = samples[:max_images]

    if not samples:
        print("No valid samples found in list file.", file=sys.stderr)
        return 1

    output_path = os.path.abspath(os.path.expanduser(output_path))
    header_path = os.path.abspath(os.path.expanduser(infer_header_path(output_path, header_path)))

    prefix_id = make_identifier(prefix)

    all_bytes = bytearray()
    offsets: List[int] = [0]
    labels: List[int] = []

    expected_w = -1
    expected_h = -1
    expected_c = 3
    converted = 0
    skipped = 0

    for _, (label, raw_img_path) in enumerate(samples):
        abs_path = resolve_img_path(raw_img_path, list_dir)
        if not os.path.exists(abs_path):
            print(f"[warn] Missing image (skipped): {abs_path}", file=sys.stderr)
            skipped += 1
            continue

        try:
            with Image.open(abs_path) as img:
                if img.mode != "RGB":
                    img = img.convert("RGB")
                width, height = img.size
                raw_bytes = img.tobytes()
        except Exception as exc:
            print(f"[warn] Failed to read image (skipped): {abs_path} ({exc})", file=sys.stderr)
            skipped += 1
            continue

        if expected_w < 0:
            expected_w = width
            expected_h = height
        elif width != expected_w or height != expected_h:
            print(
                "[warn] Skipping image with different shape "
                f"{width}x{height} (expected {expected_w}x{expected_h}): {abs_path}",
                file=sys.stderr,
            )
            skipped += 1
            continue

        all_bytes.extend(raw_bytes)
        offsets.append(len(all_bytes))
        labels.append(label)
        converted += 1

    if converted == 0:
        print("No images were converted (all skipped).", file=sys.stderr)
        return 2

    with open(output_path, "w", encoding="utf-8") as f:
        header_name = os.path.basename(header_path)

        f.write("// Auto-generated by scripts/list_to_c_arrays.py\n")
        f.write(f"// Source list: {list_path}\n")
        f.write("// Traversable dataset stored in one contiguous byte array.\n\n")
        f.write(f"#include \"{header_name}\"\n\n")

        f.write(f"const int {prefix_id}_count = {converted};\n")
        f.write(f"const int {prefix_id}_w = {expected_w};\n")
        f.write(f"const int {prefix_id}_h = {expected_h};\n")
        f.write(f"const int {prefix_id}_c = {expected_c};\n")
        f.write(f"const int {prefix_id}_image_bytes = {expected_w * expected_h * expected_c};\n")
        f.write(f"const unsigned int {prefix_id}_total_bytes = {len(all_bytes)};\n\n")

        write_unsigned_char_array(f, f"{prefix_id}_data", bytes(all_bytes))
        write_unsigned_int_array(f, f"{prefix_id}_offsets", offsets)
        write_int_array(f, f"{prefix_id}_labels", labels)

    write_header_file(
        header_path=header_path,
        prefix_id=prefix_id,
        image_count=converted,
        width=expected_w,
        height=expected_h,
        channels=expected_c,
    )

    print(f"Converted images: {converted}")
    print(f"Skipped images:   {skipped}")
    print(f"Output C file:    {output_path}")
    print(f"Output H file:    {header_path}")

    return 0 if converted > 0 else 2


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Convert all images listed in '<label> <path>' text file into C arrays "
                "as one contiguous byte buffer plus offsets/labels arrays."
        )
    )
    parser.add_argument(
        "--list",
        default="cifar10/images.list",
        help="Path to list file (default: cifar10/images.list)",
    )
    parser.add_argument(
        "--output",
        default="cifar10_images_arrays.c",
        help="Output C file path (default: cifar10_images_arrays.c)",
    )
    parser.add_argument(
        "--header",
        default=None,
        help="Output header path (default: same basename as --output with .h)",
    )
    parser.add_argument(
        "--prefix",
        default="cifar10",
        help="Prefix for generated C symbols (default: cifar10)",
    )
    parser.add_argument(
        "--max-images",
        type=int,
        default=0,
        help="Optional cap on number of images to convert (0 = all)",
    )
    return parser


def main() -> int:
    args = build_arg_parser().parse_args()
    return convert_list_to_c(
        list_path=args.list,
        output_path=args.output,
        header_path=args.header,
        prefix=args.prefix,
        max_images=args.max_images,
    )


if __name__ == "__main__":
    sys.exit(main())
