#!/usr/bin/env python3
import argparse
from pathlib import Path

import numpy as np

DEFAULT_INPUTS = 2048
DEFAULT_OUTPUTS = 512
DEFAULT_SAMPLES = 4


def write_c_array_f32(f, name: str, arr: np.ndarray, per_line: int = 8) -> None:
    flat = arr.astype(np.float32).reshape(-1)
    f.write(f"float {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        vals = ", ".join(f"{x:.8f}f" for x in chunk)
        if i + per_line >= flat.size:
            f.write(f"    {vals}\n")
        else:
            f.write(f"    {vals},\n")
    f.write("};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate FC(2048->512) synthetic vectors for bare-metal tests (fc_layer)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--samples", type=int, default=DEFAULT_SAMPLES, help="Number of samples to generate")
    parser.add_argument("--inputs", type=int, default=DEFAULT_INPUTS, help="FC layer input units (IN)")
    parser.add_argument("--outputs", type=int, default=DEFAULT_OUTPUTS, help="FC layer output units (OUT)")
    parser.add_argument("--out-dir", default="generated_data", help="Output directory for binary files")
    parser.add_argument("--weights-c", default="kernel/weights.c", help="Path to generated weights.c")
    args = parser.parse_args()

    samples = args.samples
    INPUTS = args.inputs
    OUTPUTS = args.outputs
    np.random.seed(args.seed)

    x = np.random.uniform(-1.0, 1.0, size=(samples, INPUTS)).astype(np.float32)
    w = np.random.uniform(-0.1, 0.1, size=(INPUTS * OUTPUTS,)).astype(np.float32)
    b = np.ones((OUTPUTS,), dtype=np.float32)
    labels = np.random.randint(0, OUTPUTS, size=(samples,)).astype(np.int32)
    targets = np.zeros((samples, OUTPUTS), dtype=np.float32)
    targets[np.arange(samples), labels] = 1.0

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    x.tofile(str(out_dir / "inputs.bin"))
    labels.tofile(str(out_dir / "labels.bin"))
    targets.tofile(str(out_dir / "targets.bin"))

    weights_path = Path(args.weights_c)
    weights_path.parent.mkdir(parents=True, exist_ok=True)

    with weights_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by scripts/generate_fc_test_vectors.py\n\n")
        write_c_array_f32(f, "fc1_weights", w)
        write_c_array_f32(f, "fc1_bias", b)

    print(f"Generated: {out_dir / 'inputs.bin'} ({samples} samples)")
    print(f"Generated: {out_dir / 'labels.bin'}")
    print(f"Generated: {out_dir / 'targets.bin'}")
    print(f"Generated: {weights_path}")


if __name__ == "__main__":
    main()
