#!/usr/bin/env python3
"""Generate synthetic training vectors for the conv_layer16only benchmark (pure FP16).

Default config (matches alexnet.h defaults):
  BATCH=4  C_IN=43  C_OUT=43  KERNEL=3  H=8  W=8  PAD=1

Override via CLI to benchmark different spatial / channel sizes:
  python3 generate_conv_test_vectors.py --batch 1 --c-in 64 --c-out 32 --h 1 --w 128

The number of generated samples (--batch) must equal ALEXNET_BATCHSIZE used
when compiling, so that CONV_TOTAL_SAMPLES == ALEXNET_BATCHSIZE and the
memcpy in train.c never reads past the end of the binary.

Pure-FP16 variant: weights/inputs/targets/bias are emitted as _Float16 (2 bytes),
so the embedded .bin strides and the C-side _Float16 buffers line up.
"""
import argparse
from pathlib import Path

import numpy as np


def write_c_array_f16(f, name: str, arr: np.ndarray, per_line: int = 8) -> None:
    flat = arr.astype(np.float16).reshape(-1)
    f.write(f"_Float16 {name}[{flat.size}] = {{\n")
    for i in range(0, flat.size, per_line):
        chunk = flat[i : i + per_line]
        vals = ", ".join(f"{float(x):.8f}f" for x in chunk)
        comma = "" if i + per_line >= flat.size else ","
        f.write(f"    {vals}{comma}\n")
    f.write("};\n\n")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate conv_layer16only benchmark vectors (FP16)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--seed",      type=int, default=42,   help="Random seed")
    parser.add_argument("--batch",     type=int, default=4,    help="Number of samples (== ALEXNET_BATCHSIZE)")
    parser.add_argument("--c-in",      type=int, default=43,   help="Input channels  (CONV1_IN_CHANNELS)")
    parser.add_argument("--c-out",     type=int, default=43,   help="Output channels (CONV1_OUT_CHANNELS)")
    parser.add_argument("--h",         type=int, default=8,    help="Image height == output height (same-padding)")
    parser.add_argument("--w",         type=int, default=8,    help="Image width  == output width  (same-padding)")
    parser.add_argument("--kernel",    type=int, default=3,    help="Kernel size (stays 3)")
    parser.add_argument("--out-dir",   default="generated_data", help="Output directory for binary files")
    parser.add_argument("--weights-c", default="kernel/weights.c", help="Path to generated weights.c")
    args = parser.parse_args()

    BATCH  = args.batch
    C_IN   = args.c_in
    C_OUT  = args.c_out
    H      = args.h
    W      = args.w
    KERNEL = args.kernel

    INPUT_ELEMS  = C_IN  * H * W
    OUTPUT_ELEMS = C_OUT * H * W          # same-padding: spatial dims unchanged
    WEIGHT_ELEMS = C_OUT * C_IN * KERNEL * KERNEL

    print(f"Config: BATCH={BATCH}  C_IN={C_IN}  C_OUT={C_OUT}  H={H}  W={W}  K={KERNEL}x{KERNEL}")
    print(f"  input/sample  : {INPUT_ELEMS:>8} f16 = {INPUT_ELEMS*2/1024:.1f} KB")
    print(f"  output/sample : {OUTPUT_ELEMS:>8} f16 = {OUTPUT_ELEMS*2/1024:.1f} KB")
    print(f"  weights       : {WEIGHT_ELEMS:>8} f16 = {WEIGHT_ELEMS*2/1024:.1f} KB")

    np.random.seed(args.seed)

    inputs  = np.random.uniform(-1.0,  1.0, size=(BATCH, INPUT_ELEMS)).astype(np.float16)
    targets = np.random.uniform(-1.0,  1.0, size=(BATCH, OUTPUT_ELEMS)).astype(np.float16)
    labels  = np.random.randint(0, C_OUT, size=(BATCH,)).astype(np.int32)
    weights = np.random.uniform(-0.1, 0.1, size=(WEIGHT_ELEMS,)).astype(np.float16)
    bias    = np.ones((C_OUT,), dtype=np.float16)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    inputs.tofile(str(out_dir / "inputs.bin"))
    targets.tofile(str(out_dir / "targets.bin"))
    labels.tofile(str(out_dir / "labels.bin"))

    weights_path = Path(args.weights_c)
    weights_path.parent.mkdir(parents=True, exist_ok=True)
    with weights_path.open("w", encoding="ascii") as f:
        f.write("// Auto-generated by scripts/generate_conv_test_vectors.py (FP16)\n")
        f.write(f"// Config: C_IN={C_IN} C_OUT={C_OUT} H={H} W={W} K={KERNEL} BATCH={BATCH}\n\n")
        write_c_array_f16(f, "conv1_weights", weights)
        write_c_array_f16(f, "conv1_bias",    bias)

    print(f"\nGenerated (FP16):")
    print(f"  {out_dir / 'inputs.bin'}  ({BATCH}x{INPUT_ELEMS} f16)")
    print(f"  {out_dir / 'targets.bin'} ({BATCH}x{OUTPUT_ELEMS} f16)")
    print(f"  {out_dir / 'labels.bin'}  ({BATCH} int32)")
    print(f"  {weights_path}")


if __name__ == "__main__":
    main()
