//
// File:        train.c
// Description: Convolution-layer training flow
// Author:      Haris Wang
//
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <math.h>
#include <string.h>
#include "alexnet.h"
#include "runtime.h"
#include "weights.h"
#ifdef SPIKE
#include <printf.h>
#elif defined ARA_LINUX
#include <stdio.h>
#else
#include "printf.h"
#endif

#define MAX(a,b) (((a) > (b)) ? (a) : (b))
#define MIN(a,b) (((a) < (b)) ? (a) : (b))

// train.c is compiled with -O0 in this app profile; bind timer calls to
// runtime counter primitives to avoid unresolved inline symbols.
static inline int64_t alexnet_cycle_count_local(void)
{
    int64_t cycle_count = 0;
    asm volatile("fence; csrr %0, cycle" : "=r"(cycle_count));
    return cycle_count;
}

#define LEARNING_RATE 0.00001f

// Mixed-precision loss scaling: the gradient seed is multiplied by LOSS_SCALE in
// the loss function to keep FP16 gradients out of the subnormal range, then
// unscaled by the same factor in the weight update. Must be identical here and
// in conv_layer/kernel/train.c for the two flows to match.
#define LOSS_SCALE 1024.0f

#ifndef ALEXNET_USE_MOMENTUM
#if defined(SPIKE)
#define ALEXNET_USE_MOMENTUM 0
#else
#define ALEXNET_USE_MOMENTUM 1
#endif
#endif

#ifndef ALEXNET_MAX_STEPS
#define ALEXNET_MAX_STEPS 0
#endif

#if defined(ALEXNET_LAYER_LOGS) && !defined(SPIKE)
#define ALEXNET_LOG_LAYER(...) printf_(__VA_ARGS__)
#else
#define ALEXNET_LOG_LAYER(...)
#endif

#ifndef ALEXNET_STATIC_MAX_BATCH
#ifdef ALEXNET_BATCHSIZE
#define ALEXNET_STATIC_MAX_BATCH ALEXNET_BATCHSIZE
#else
#define ALEXNET_STATIC_MAX_BATCH 4
#endif
#endif

// Must match the number of samples generated by the Python script (--batch arg).
// Defaults to ALEXNET_BATCHSIZE so one full batch is always available.
#ifndef CONV_TOTAL_SAMPLES
#define CONV_TOTAL_SAMPLES ALEXNET_BATCHSIZE
#endif
#define CONV1_PAD (CONV1_PADDING)
#define CONV1_PADDED_H (CONV1_IN_H + 2 * CONV1_PAD)
#define CONV1_PADDED_W (CONV1_IN_W + 2 * CONV1_PAD)
#define CONV1_PADDED_IN_UNITS (CONV1_IN_CHANNELS * CONV1_PADDED_H * CONV1_PADDED_W)
#define CONV1_XCOL_PER_IMG (CONV1_IN_CHANNELS * CONV1_KERNEL_L * CONV1_KERNEL_L * CONV1_OUT_W * CONV1_OUT_H)

static _Float16 d_conv1_weights[CONV1_WEIGHT_ELEMS];
static _Float16 d_conv1_bias[CONV1_OUT_CHANNELS];
static _Float16 v_conv1_weights[CONV1_WEIGHT_ELEMS];
static _Float16 v_conv1_bias[CONV1_OUT_CHANNELS];

static _Float16 d_conv1_output_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_OUT_UNITS];
static _Float16 d_conv1_input_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_IN_UNITS];
static _Float16 d_conv1_input_pad_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_PADDED_IN_UNITS];

static _Float16 train_input_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_IN_UNITS];
static _Float16 train_input_pad_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_PADDED_IN_UNITS];
static _Float16 train_targets_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_OUT_UNITS];

static _Float16 compare_output_ref[ALEXNET_STATIC_MAX_BATCH * CONV1_OUT_UNITS];
static _Float16 compare_output_pad[ALEXNET_STATIC_MAX_BATCH * CONV1_OUT_UNITS];
static _Float16 compare_input_col_buf[ALEXNET_STATIC_MAX_BATCH * CONV1_XCOL_PER_IMG];

static int64_t last_loss_cycles = 0;
static int64_t last_zero_dinput_cycles = 0;
static int64_t last_backward_cycles = 0;
static int64_t last_update_cycles = 0;
static int64_t last_precompute_cycles = 0;
static conv_backward_cycle_breakdown last_conv_backward_breakdown = {0,0,0};
static int64_t last_conv_backward_total_cycles = 0;

static void zero_f16(_Float16 *buf, int n)
{
    memset(buf, 0, (size_t)n * sizeof(_Float16));
}
static inline void memcpy_vectorized_f16(_Float16 *dst, const _Float16 *src, size_t n_elements) {
    while (n_elements > 0) {
        size_t vl;
        // Χρησιμοποιούμε m8 για να δεσμεύσουμε 8 Vector Registers μαζί!
        asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n_elements));
        
        // Φόρτωση και Αποθήκευση στη μέγιστη ταχύτητα του διαύλου μνήμης
        asm volatile("vle16.v v16, (%0)" :: "r"(src));
        asm volatile("vse16.v v16, (%0)" :: "r"(dst));
        
        src += vl;
        dst += vl;
        n_elements -= vl;
    }
}
static void zero_f16_vec(_Float16 *buf, int n)
{
    size_t max_vl;
    asm volatile("vsetvli %0, zero, e16, m8, ta, ma" : "=r"(max_vl));
    asm volatile("vmv.v.i v8, 0");

    _Float16 *ptr = buf;
    while (n > 0) {
        size_t vl;
        asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n));
        asm volatile("vse16.v v8, (%0)" :: "r"(ptr));
        ptr += vl;
        n -= vl;
    }
}

static void pad_tensor_vectorized(_Float16 *dst, const _Float16 *src, int batch, int channels, int in_h, int in_w, int pad)
{
    int out_h = in_h + 2 * pad;
    int out_w = in_w + 2 * pad;
    size_t total = (size_t)batch * (size_t)channels * (size_t)out_h * (size_t)out_w;
    
    // ---------------------------------------------------------
    // 1. Vectorized Memset (Μηδενισμός όλου του dst)
    // ---------------------------------------------------------
    size_t n_zero = total;
    _Float16 *dst_zero = dst;
    
    // Βάζουμε 0 σε όλους τους lanes του τεράστιου καταχωρητή v8 (m8)
    // `vsetvli zero, zero` (rd = x0 AND rs1 = x0) KEEPS the caller's vl and only
    // changes vtype -- it does NOT select VLMAX. The splat then fills just those
    // lanes while the drain loop below stores at vl = min(n, VLMAX), writing the
    // untouched lanes out as GARBAGE instead of zeros. rd != x0 with rs1 = x0
    // requests AVL = ~0 -> vl = VLMAX, so the whole register group is zeroed.
    size_t vlmax_p;
    asm volatile("vsetvli %0, zero, e16, m8, ta, ma" : "=r"(vlmax_p));
    asm volatile("vmv.v.i v8, 0");

    while (n_zero > 0) {
        size_t vl;
        asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n_zero));
        asm volatile("vse16.v v8, (%0)" :: "r"(dst_zero));
        dst_zero += vl;
        n_zero -= vl;
    }

    // ---------------------------------------------------------
    // 2. Vectorized Memcpy (Αντιγραφή των πραγματικών pixels)
    // ---------------------------------------------------------
    int in_plane = in_h * in_w;
    int out_plane = out_h * out_w;
    
    for (int b = 0; b < batch; b++) {
        const _Float16 *src_b = src + b * channels * in_plane;
        _Float16 *dst_b = dst + b * channels * out_plane;
        
        for (int c = 0; c < channels; c++) {
            const _Float16 *src_c = src_b + c * in_plane;
            _Float16 *dst_c = dst_b + c * out_plane + pad * out_w + pad;
            
            for (int y = 0; y < in_h; y++) {
                const _Float16 *s_ptr = src_c + y * in_w;
                _Float16 *d_ptr = dst_c + y * out_w;
                int n_copy = in_w;
                
                // Αντιγραφή της γραμμής με Vector Load -> Vector Store
                while (n_copy > 0) {
                    size_t vl;
                    asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n_copy));
                    asm volatile("vle16.v v16, (%0)" :: "r"(s_ptr)); // Διάβασε
                    asm volatile("vse16.v v16, (%0)" :: "r"(d_ptr)); // Γράψε
                    s_ptr += vl;
                    d_ptr += vl;
                    n_copy -= vl;
                }
            }
        }
    }
}

static void unpad_tensor_vectorized(_Float16 *dst, const _Float16 *src, int batch, int channels, int in_h, int in_w, int pad)
{
    int padded_h = in_h + 2 * pad;
    int padded_w = in_w + 2 * pad;
    int out_plane = in_h * in_w;
    int in_plane = padded_h * padded_w;
    
    for (int b = 0; b < batch; b++) {
        const _Float16 *src_b = src + b * channels * in_plane;
        _Float16 *dst_b = dst + b * channels * out_plane;
        
        for (int c = 0; c < channels; c++) {
            const _Float16 *src_c = src_b + c * in_plane + pad * padded_w + pad;
            _Float16 *dst_c = dst_b + c * out_plane;
            
            for (int y = 0; y < in_h; y++) {
                const _Float16 *s_ptr = src_c + y * padded_w;
                _Float16 *d_ptr = dst_c + y * in_w;
                int n_copy = in_w;
                
                // Αφαίρεση του padding αντιγράφοντας μόνο το in_w με Vectors
                while (n_copy > 0) {
                    size_t vl;
                    asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n_copy));
                    asm volatile("vle16.v v16, (%0)" :: "r"(s_ptr)); // Διάβασε
                    asm volatile("vse16.v v16, (%0)" :: "r"(d_ptr)); // Γράψε
                    s_ptr += vl;
                    d_ptr += vl;
                    n_copy -= vl;
                }
            }
        }
    }
}

static void compare_padding_paths(alexnet *net, const _Float16 *input_unpadded, const _Float16 *input_padded)
{
    (void)input_unpadded;

    conv_op old_op = net->conv1;
    old_op.input = (_Float16 *)input_padded;
    old_op.output = compare_output_ref;
    old_op.in_w = CONV1_PADDED_W;
    old_op.in_h = CONV1_PADDED_H;
    old_op.in_units = CONV1_PADDED_IN_UNITS;
    old_op.padding = 0;
    old_op.layer_id = 5;
    old_op.input_col = compare_input_col_buf;
    conv_op_forward_im2col(&old_op);

    conv_op new_op = old_op;
    new_op.output = compare_output_pad;
    new_op.input_col = NULL;
    conv_op_forward(&new_op);

    int total = net->batchsize * new_op.out_units;
    _Float16 max_diff = 0.0f;
    int max_idx = -1;
    for (int i = 0; i < total; i++) {
        _Float16 diff = fabsf(compare_output_ref[i] - compare_output_pad[i]);
        if (diff > max_diff) {
            max_diff = diff;
            max_idx = i;
        }
    }
    // (float) cast is required: a bare _Float16 argument is not promoted and
    // would print as 0.000000 (see the note on mse_loss_vec below).
    printf_("padding compare: max_abs_diff=%.6f idx=%d\n", (float)max_diff, max_idx);
}

// Returns the loss as `float`, NOT `_Float16`. All the arithmetic below stays
// in FP16 (this is the pure-FP16 app); only the reported scalar is widened.
// _Float16 is not subject to C's default argument promotion, so handing one to
// a variadic printf_("%.6f") leaves a half in a slot the callee reads as a
// double -- it formats as exactly 0.000000. That is why this app printed
// "loss: 0.000000" while conv_layer32 printed 0.771228.
static float mse_loss_vec(_Float16 *delta_preds, const _Float16 *preds, const _Float16 *targets, int units, int batch_size)
{
    int total_elems = batch_size * units;
    _Float16 scale_factor = 0.5f / (_Float16)total_elems;

    size_t max_vl;
    asm volatile("vsetvli %0, zero, e16, m8, tu, ma" : "=r"(max_vl));
    asm volatile("vmv.v.i v8, 0");

    int n = total_elems;
    const _Float16 *p_ptr = preds;
    const _Float16 *t_ptr = targets;
    _Float16 *d_ptr = delta_preds;
    // Gradient seed scaled by LOSS_SCALE (unscaled again in momentum_sgd_vec).
    // Loss value below is accumulated from the UNSCALED delta, so it stays true.
    _Float16 grad_scale = LOSS_SCALE / (_Float16)total_elems;

    while (n > 0) {
        size_t vl;
        asm volatile("vsetvli %0, %1, e16, m8, tu, ma" : "=r"(vl) : "r"(n));
        asm volatile("vle16.v v16, (%0)" :: "r"(p_ptr));
        asm volatile("vle16.v v24, (%0)" :: "r"(t_ptr));

        asm volatile("vfsub.vv v16, v16, v24");
        asm volatile("vfmacc.vv v8, v16, v16");
        asm volatile("vfmul.vf v16, v16, %0" :: "f"(grad_scale));
        asm volatile("vse16.v v16, (%0)" :: "r"(d_ptr));

        p_ptr += vl;
        t_ptr += vl;
        d_ptr += vl;
        n -= vl;
    }

    // A reduction reads only vl elements of vs2, and `vsetvli zero, zero` keeps
    // the loop's last (possibly partial) chunk -- so accumulator lanes above
    // that tail were silently dropped and the loss came out too small.
    asm volatile("vsetvli %0, zero, e16, m8, tu, ma" : "=r"(max_vl));
    asm volatile("vmv.v.i v0, 0");
    asm volatile("vfredsum.vs v0, v8, v0");
    _Float16 sum_squares;
    asm volatile("vfmv.f.s %0, v0" : "=f"(sum_squares));

    // Multiply in FP16 (unchanged numerics), then widen purely for reporting.
    const _Float16 mse_loss_h = sum_squares * scale_factor;
    float mse_loss_val = (float)mse_loss_h;
    ALEXNET_LOG_LAYER("MSE loss computed: %f\n", mse_loss_val);
    return mse_loss_val;
}

static inline void CLIP(_Float16 *x, _Float16 down, _Float16 up)
{
    *x = MIN(up, MAX(down, *x));
}

static void momentum_sgd_vec(_Float16 *w, _Float16 *v_w, const _Float16 *d_w, int units)
{
    _Float16 lr = LEARNING_RATE;
    // Unscale the loss-scaled gradient before it is used, so clipping/momentum
    // act on the true gradient. Pairs with grad_scale in the loss function.
    _Float16 inv_loss_scale = 1.0f / LOSS_SCALE;
    int n = units;

#if ALEXNET_USE_MOMENTUM
    _Float16 momentum = 0.9f;
    _Float16 clip_min = -1.0f;
    _Float16 clip_max = 1.0f;

    while (n > 0) {
        size_t vl;
        asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n));

        asm volatile("vle16.v v8,  (%0)" :: "r"(v_w));
        asm volatile("vle16.v v16, (%0)" :: "r"(d_w));
        asm volatile("vle16.v v24, (%0)" :: "r"(w));

        asm volatile("vfmul.vf v16, v16, %0" :: "f"(inv_loss_scale));
        asm volatile("vfmul.vf v8, v8, %0" :: "f"(momentum));
        asm volatile("vfnmsac.vf v8, %0, v16" :: "f"(lr));
        asm volatile("vfmax.vf v8, v8, %0" :: "f"(clip_min));
        asm volatile("vfmin.vf v8, v8, %0" :: "f"(clip_max));
        asm volatile("vfadd.vv v24, v24, v8");

        asm volatile("vse16.v v8,  (%0)" :: "r"(v_w));
        asm volatile("vse16.v v24, (%0)" :: "r"(w));

        w += vl;
        v_w += vl;
        d_w += vl;
        n -= vl;
    }
#else
    (void)v_w;
    while (n > 0) {
        size_t vl;
        asm volatile("vsetvli %0, %1, e16, m8, ta, ma" : "=r"(vl) : "r"(n));

        asm volatile("vle16.v v8,  (%0)" :: "r"(w));
        asm volatile("vle16.v v16, (%0)" :: "r"(d_w));
        asm volatile("vfmul.vf v16, v16, %0" :: "f"(inv_loss_scale));
        asm volatile("vfnmsac.vf v8, %0, v16" :: "f"(lr));
        asm volatile("vse16.v v8,  (%0)" :: "r"(w));

        w += vl;
        d_w += vl;
        n -= vl;
    }
#endif
}

static void gradient_descent(alexnet *net)
{
    if (!net->trainable.conv1)
        return;

    net->conv1.weights = conv1_weights;
    net->conv1.bias = conv1_bias;
    net->conv1.d_weights = d_conv1_weights;
    net->conv1.d_bias = d_conv1_bias;

    momentum_sgd_vec(conv1_weights, v_conv1_weights, d_conv1_weights, CONV1_WEIGHT_ELEMS);
    momentum_sgd_vec(conv1_bias, v_conv1_bias, d_conv1_bias, CONV1_OUT_CHANNELS);
}

void calloc_alexnet_d_params(alexnet *net)
{
    net->conv1.d_weights = d_conv1_weights;
    net->conv1.d_bias = d_conv1_bias;
    zero_f16_vec(net->conv1.d_weights, CONV1_WEIGHT_ELEMS);
    zero_f16_vec(net->conv1.d_bias, CONV1_OUT_CHANNELS);
}

void free_alexnet_d_params(alexnet *net)
{
    net->conv1.d_weights = NULL;
    net->conv1.d_bias = NULL;
}

void backward_alexnet(alexnet *net, const int *batch_Y, const _Float16 *batch_targets, float *loss_out)
{
    (void)batch_Y;

    if (net->batchsize > ALEXNET_STATIC_MAX_BATCH) {
        printf_("Error: batchsize %d exceeds static max batch %d\n", net->batchsize, ALEXNET_STATIC_MAX_BATCH);
        exit(1);
    }

    calloc_alexnet_d_params(net);

    _Float16 *curr_grad = d_conv1_output_buf;
    _Float16 *next_grad = d_conv1_input_pad_buf;
    float loss_val = 0.0f;
    int64_t t0 = 0;

    t0 = alexnet_cycle_count_local();
    loss_val = mse_loss_vec(curr_grad, net->conv1.output, batch_targets, net->conv1.out_units, net->batchsize);
    last_loss_cycles = alexnet_cycle_count_local() - t0;

    net->conv1.d_input = next_grad;
    t0 = alexnet_cycle_count_local();
    zero_f16_vec(net->conv1.d_input, net->batchsize * net->conv1.in_units);
    last_zero_dinput_cycles = alexnet_cycle_count_local() - t0;
    net->conv1.d_output = curr_grad;

    t0 = alexnet_cycle_count_local();
    if (net->trainable.conv1) {
        conv_op_backward_full_profile(&(net->conv1), &last_conv_backward_breakdown);
    } else {
        last_conv_backward_breakdown.d_input_cycles = 0;
        last_conv_backward_breakdown.d_bias_cycles = 0;
        last_conv_backward_breakdown.d_weights_im2col_cycles = 0;
        last_conv_backward_breakdown.d_weights_cycles = 0;
        conv_op_backward_input_only(&(net->conv1));
    }
    last_backward_cycles = alexnet_cycle_count_local() - t0;
    last_conv_backward_total_cycles = last_conv_backward_breakdown.d_input_cycles +
                                     last_conv_backward_breakdown.d_bias_cycles +
                                     last_conv_backward_breakdown.d_weights_cycles;

    unpad_tensor_vectorized(d_conv1_input_buf, d_conv1_input_pad_buf,
                            net->batchsize, CONV1_IN_CHANNELS, CONV1_IN_H, CONV1_IN_W, CONV1_PAD);
    net->conv1.d_input = d_conv1_input_buf;

    t0 = alexnet_cycle_count_local();
    gradient_descent(net);
    last_update_cycles = alexnet_cycle_count_local() - t0;

    if (loss_out != NULL)
        *loss_out = loss_val;
}

void alexnet_train(alexnet *net, int epochs)
{
    if (net->batchsize > ALEXNET_STATIC_MAX_BATCH) {
        printf_("Error: batchsize %d exceeds static max batch %d\n", net->batchsize, ALEXNET_STATIC_MAX_BATCH);
        exit(1);
    }

    net->input = train_input_pad_buf;
    _Float16 *batch_targets = train_targets_buf;
    net->conv1.padding = 0;
    net->conv1.in_w = CONV1_PADDED_W;
    net->conv1.in_h = CONV1_PADDED_H;
    net->conv1.in_units = CONV1_PADDED_IN_UNITS;

    int dataset_count = CONV_TOTAL_SAMPLES;
    int steps_per_epoch = dataset_count / net->batchsize;
    if (dataset_count % net->batchsize) steps_per_epoch++;
    if (steps_per_epoch <= 0) steps_per_epoch = 1;
    if (ALEXNET_MAX_STEPS > 0 && steps_per_epoch > ALEXNET_MAX_STEPS)
        steps_per_epoch = ALEXNET_MAX_STEPS;

    // ================================================================
    // PRECOMPUTE gather offsets for vectorized img2col (ONE TIME ONLY)
    // ================================================================
    // Function returns compute-only cycles; timing it from here would instead
    // measure its internal DEBUG printf_ calls (HTIF-bound, ~5000 cyc/char).
    last_precompute_cycles = precompute_img2col_offsets_static(&(net->conv1));
    printf_("precomputation cycles: %ld\n", last_precompute_cycles);
    printf_("DEBUG: After precomputation, total_gather_elements should be set\n");

    // ================================================================
    // VERIFY img2col implementations - run once before training
    // ================================================================
    // Load first sample for verification
    // {
    //     size_t input_elements = (size_t)net->batchsize * CONV1_IN_UNITS;
    //     memcpy_vectorized_f16(train_input_buf, test_inputs, input_elements);
    //     pad_tensor_vectorized(train_input_pad_buf, train_input_buf,
    //                           net->batchsize, net->conv1.in_channels,
    //                           net->conv1.in_h, net->conv1.in_w,
    //                           net->conv1.padding);
    //     net->conv1.input = train_input_pad_buf;
    //     verify_img2col_implementations(&(net->conv1), 
    //                                   train_input_pad_buf + 0 * net->conv1.in_units);
    // }

    ALEXNET_LOG_LAYER("\n\n>>>>>>>>>>>>>>>>>>>>>>>>>>> training begin >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n");
    for (int e = 0; e < epochs; e++) {
        printf_(">>>>>>>>>>>>>>>>>>>> epoch %d >>>>>>>>>>>>>>>>>>>>>>\n", e + 1);
        static int compare_once = 0;
        for (int b = 0; b < steps_per_epoch; b++) {
            float step_loss = 0.0f;
            int64_t prep_cycles = 0;
            int64_t forward_cycles = 0;
            int64_t t0 = 0;

            t0 = alexnet_cycle_count_local();
            int sample_offset = (b * net->batchsize) % dataset_count;
            
            // --- VECTORIZED MEMCPY ΓΙΑ ΤΟ INPUT ---
            size_t input_elements = (size_t)net->batchsize * CONV1_IN_UNITS;
            memcpy_vectorized_f16(train_input_buf, 
                                  test_inputs + sample_offset * CONV1_IN_UNITS, 
                                  input_elements);
                                  
            // --- VECTORIZED MEMCPY ΓΙΑ ΤΑ TARGETS ---
            size_t target_elements = (size_t)net->batchsize * CONV1_OUT_UNITS;
            memcpy_vectorized_f16(batch_targets, 
                                  test_targets + sample_offset * CONV1_OUT_UNITS, 
                                  target_elements);
            
            // --- VECTORIZED PADDING ---
            pad_tensor_vectorized(train_input_pad_buf, train_input_buf,
                                  net->batchsize, CONV1_IN_CHANNELS, 
                                  CONV1_IN_H, CONV1_IN_W, CONV1_PAD);
                                  
            prep_cycles = alexnet_cycle_count_local() - t0;

            t0 = alexnet_cycle_count_local();
            forward_alexnet(net);
            forward_cycles = alexnet_cycle_count_local() - t0;

            t0 = alexnet_cycle_count_local();
            backward_alexnet(net, NULL, batch_targets, &step_loss);
            (void)t0;

            printf_("cycles[epoch %d batch %d/%d]: prep=%ld, forward=%ld, loss=%ld, zero_d_input=%ld, backward=%ld, update=%ld\n",
                    e + 1, b + 1, steps_per_epoch,
                    prep_cycles, forward_cycles,
                    last_loss_cycles, last_zero_dinput_cycles,
                    last_backward_cycles, last_update_cycles);
            printf_("conv backward breakdown: d_input=%ld, d_bias=%ld, d_weights_im2col=%ld, d_weights_total=%ld, total=%ld\n",
                    last_conv_backward_breakdown.d_input_cycles,
                    last_conv_backward_breakdown.d_bias_cycles,
                    last_conv_backward_breakdown.d_weights_im2col_cycles,
                    last_conv_backward_breakdown.d_weights_cycles,
                    last_conv_backward_total_cycles);
            printf_("epoch %d step %d/%d loss: %.6f\n", e + 1, b + 1, steps_per_epoch, step_loss);
        }
    }
    ALEXNET_LOG_LAYER(">>>>>>>>>>>>>>>>>>>>>>>>>>>> training end >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n\n");
    printf_("===== Training Summary =====\n");
    printf_("precomputation cycles (one-time): %ld\n", last_precompute_cycles);
    printf_("============================\n\n");
}

void alexnet_test(alexnet *net)
{
    if (net->batchsize > ALEXNET_STATIC_MAX_BATCH) {
        printf_("Error: batchsize %d exceeds static max batch %d\n", net->batchsize, ALEXNET_STATIC_MAX_BATCH);
        exit(1);
    }

        net->input = train_input_pad_buf;
        net->conv1.padding = 0;
        net->conv1.in_w = CONV1_PADDED_W;
        net->conv1.in_h = CONV1_PADDED_H;
        net->conv1.in_units = CONV1_PADDED_IN_UNITS;
        
        // --- VECTORIZED MEMCPY FOR INPUT ---
        memcpy_vectorized_f16(train_input_buf,
            test_inputs,
            (size_t)net->batchsize * CONV1_IN_UNITS);
            
        // --- VECTORIZED MEMCPY FOR TARGETS ---
        memcpy_vectorized_f16(train_targets_buf,
           test_targets,
           (size_t)net->batchsize * CONV1_OUT_UNITS);
           
        // --- VECTORIZED PADDING ---
        pad_tensor_vectorized(train_input_pad_buf, train_input_buf,
             net->batchsize, CONV1_IN_CHANNELS, CONV1_IN_H, CONV1_IN_W, CONV1_PAD);

    forward_alexnet(net);
    float loss = mse_loss_vec(d_conv1_output_buf, net->conv1.output, train_targets_buf,
                              net->conv1.out_units, net->batchsize);
    printf_("test loss: %.6f\n", loss);
}

void compute_batch_metrics(const int *preds, const int *labels, int batchsize)
{
    (void)preds;
    (void)labels;
    (void)batchsize;
}