#ifndef WEIGHTS_H
#define WEIGHTS_H

#include "alexnet.h"

// From weights.c (auto-generated by scripts/generate_conv_test_vectors.py)
extern _Float16 conv1_weights[CONV1_WEIGHT_ELEMS];
extern _Float16 conv1_bias[CONV1_OUT_CHANNELS];

// From the assembly file (.incbin)
extern const _Float16 test_inputs[];
extern const _Float16 test_targets[];
extern const int test_labels[];

#endif