#ifndef WEIGHTS_H
#define WEIGHTS_H

#include "alexnet.h"

// From weights.c (auto-generated by scripts/generate_conv_test_vectors.py)
extern float conv1_weights[CONV1_WEIGHT_ELEMS];
extern float conv1_bias[CONV1_OUT_CHANNELS];

// From the assembly file (.incbin)
extern const float test_inputs[];
extern const float test_targets[];
extern const int test_labels[];

#endif