// Auto-generated by scripts/generate_conv_test_vectors.py
// Config: C_IN=1 C_OUT=1 H=1 W=16 K=3 BATCH=1

float conv1_weights[9] = {
    -0.08698968f, 0.08977710f, 0.09312641f, 0.06167947f, -0.03907724f, -0.08046558f, 0.03684660f, -0.01196950f,
    -0.07559235f
};

float conv1_bias[1] = {
    1.00000000f
};

